on: pull_request
name: PR
jobs:
  gitHubActionForNpm:
    name: GitHub Action for npm
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: GitHub Action for npm
      uses: actions/npm@59b64a598378f31e49cb76f27d6f3312b582f680
      with:
        entrypoint: build
